version: 2.1
orbs: 
  php: circleci/php@1.1.0
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/php:8.1.9
  resource_class: medium

jobs:
  assemble:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Run Unit tests
          command: |
            curl https://pbs.twimg.com/profile_images/1542870123366584320/-UmHlgaJ_400x400.png > test.png
            vendor/bin/phpunit src/test/Api
      - run: 
          name: show src files 
          command: ls -Rlt src

  deploy:
    <<: *defaults
    steps:
      - checkout

workflows:
  version: 2

  verify_codegen:
    jobs:
      - assemble:
        filters:
          branches:
            only: /^codegen-.*$/
  
  deploy:
      jobs:
        - assemble:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v[0-9]+.*$/ 
        - deploy:
            requires:
              - assemble
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v[0-9]+.*$/
