<?php
/**
 * CreateAuthorizationRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Finix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Finix\Model;

use \ArrayAccess;
use \Finix\ObjectSerializer;

/**
 * CreateAuthorizationRequest Class Doc Comment
 *
 * @category Class
 * @description Create an &#x60;Authorization&#x60; resource.
 * @package  Finix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CreateAuthorizationRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateAuthorizationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tags' => 'array<string,string>',
        'amount' => 'int',
        'currency' => '\Finix\Model\Currency',
        'idempotency_id' => 'string',
        'merchant' => 'string',
        'merchant_identity' => 'string',
        'processor' => 'string',
        'source' => 'string',
        'additional_purchase_data' => '\Finix\Model\AdditionalPurchaseData',
        'fraud_session_id' => 'string',
        'sub_type' => '\Finix\Model\SubTypeTransfer',
        'operation_key' => '\Finix\Model\OperationKey',
        'device' => 'string',
        'additional_buyer_charges' => '\Finix\Model\AdditionalBuyerCharges',
        '_3d_secure_authentication' => '\Finix\Model\CreateAuthorizationRequest3dSecureAuthentication'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tags' => null,
        'amount' => 'int64',
        'currency' => null,
        'idempotency_id' => null,
        'merchant' => null,
        'merchant_identity' => null,
        'processor' => null,
        'source' => null,
        'additional_purchase_data' => null,
        'fraud_session_id' => null,
        'sub_type' => null,
        'operation_key' => null,
        'device' => null,
        'additional_buyer_charges' => null,
        '_3d_secure_authentication' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tags' => 'tags',
        'amount' => 'amount',
        'currency' => 'currency',
        'idempotency_id' => 'idempotency_id',
        'merchant' => 'merchant',
        'merchant_identity' => 'merchant_identity',
        'processor' => 'processor',
        'source' => 'source',
        'additional_purchase_data' => 'additional_purchase_data',
        'fraud_session_id' => 'fraud_session_id',
        'sub_type' => 'sub_type',
        'operation_key' => 'operation_key',
        'device' => 'device',
        'additional_buyer_charges' => 'additional_buyer_charges',
        '_3d_secure_authentication' => '3d_secure_authentication'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tags' => 'setTags',
        'amount' => 'setAmount',
        'currency' => 'setCurrency',
        'idempotency_id' => 'setIdempotencyId',
        'merchant' => 'setMerchant',
        'merchant_identity' => 'setMerchantIdentity',
        'processor' => 'setProcessor',
        'source' => 'setSource',
        'additional_purchase_data' => 'setAdditionalPurchaseData',
        'fraud_session_id' => 'setFraudSessionId',
        'sub_type' => 'setSubType',
        'operation_key' => 'setOperationKey',
        'device' => 'setDevice',
        'additional_buyer_charges' => 'setAdditionalBuyerCharges',
        '_3d_secure_authentication' => 'set3dSecureAuthentication'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tags' => 'getTags',
        'amount' => 'getAmount',
        'currency' => 'getCurrency',
        'idempotency_id' => 'getIdempotencyId',
        'merchant' => 'getMerchant',
        'merchant_identity' => 'getMerchantIdentity',
        'processor' => 'getProcessor',
        'source' => 'getSource',
        'additional_purchase_data' => 'getAdditionalPurchaseData',
        'fraud_session_id' => 'getFraudSessionId',
        'sub_type' => 'getSubType',
        'operation_key' => 'getOperationKey',
        'device' => 'getDevice',
        'additional_buyer_charges' => 'getAdditionalBuyerCharges',
        '_3d_secure_authentication' => 'get3dSecureAuthentication'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PROCESSOR_AFFIPAY_V1 = 'AFFIPAY_V1';
    public const PROCESSOR_CHECKOUT_V1 = 'CHECKOUT_V1';
    public const PROCESSOR_DUMMY_V1 = 'DUMMY_V1';
    public const PROCESSOR_ELAVON_V1 = 'ELAVON_V1';
    public const PROCESSOR_EXPRESS_V1 = 'EXPRESS_V1';
    public const PROCESSOR_FINIX_VISA_SANDBOX_V1 = 'FINIX_VISA_SANDBOX_V1';
    public const PROCESSOR_LITLE_V1 = 'LITLE_V1';
    public const PROCESSOR_MASTERCARD_V1 = 'MASTERCARD_V1';
    public const PROCESSOR_MICROBILT_V1 = 'MICROBILT_V1';
    public const PROCESSOR_MYTHICAL_V1 = 'MYTHICAL_V1';
    public const PROCESSOR_NMI_V1 = 'NMI_V1';
    public const PROCESSOR_SKRILL_V1 = 'SKRILL_V1';
    public const PROCESSOR_STRIPE_V1 = 'STRIPE_V1';
    public const PROCESSOR_TRIPOS_CLOUD_V1 = 'TRIPOS_CLOUD_V1';
    public const PROCESSOR_TRIPOS_MOBILE_V1 = 'TRIPOS_MOBILE_V1';
    public const PROCESSOR_TRULIOO_V1 = 'TRULIOO_V1';
    public const PROCESSOR_VANTIV_V1 = 'VANTIV_V1';
    public const PROCESSOR_VISA_V1 = 'VISA_V1';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProcessorAllowableValues()
    {
        return [
            self::PROCESSOR_AFFIPAY_V1,
            self::PROCESSOR_CHECKOUT_V1,
            self::PROCESSOR_DUMMY_V1,
            self::PROCESSOR_ELAVON_V1,
            self::PROCESSOR_EXPRESS_V1,
            self::PROCESSOR_FINIX_VISA_SANDBOX_V1,
            self::PROCESSOR_LITLE_V1,
            self::PROCESSOR_MASTERCARD_V1,
            self::PROCESSOR_MICROBILT_V1,
            self::PROCESSOR_MYTHICAL_V1,
            self::PROCESSOR_NMI_V1,
            self::PROCESSOR_SKRILL_V1,
            self::PROCESSOR_STRIPE_V1,
            self::PROCESSOR_TRIPOS_CLOUD_V1,
            self::PROCESSOR_TRIPOS_MOBILE_V1,
            self::PROCESSOR_TRULIOO_V1,
            self::PROCESSOR_VANTIV_V1,
            self::PROCESSOR_VISA_V1,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['tags'] = $data['tags'] ?? null;
        $this->container['amount'] = $data['amount'] ?? null;
        $this->container['currency'] = $data['currency'] ?? null;
        $this->container['idempotency_id'] = $data['idempotency_id'] ?? null;
        $this->container['merchant'] = $data['merchant'] ?? null;
        $this->container['merchant_identity'] = $data['merchant_identity'] ?? null;
        $this->container['processor'] = $data['processor'] ?? null;
        $this->container['source'] = $data['source'] ?? null;
        $this->container['additional_purchase_data'] = $data['additional_purchase_data'] ?? null;
        $this->container['fraud_session_id'] = $data['fraud_session_id'] ?? null;
        $this->container['sub_type'] = $data['sub_type'] ?? null;
        $this->container['operation_key'] = $data['operation_key'] ?? null;
        $this->container['device'] = $data['device'] ?? null;
        $this->container['additional_buyer_charges'] = $data['additional_buyer_charges'] ?? null;
        $this->container['_3d_secure_authentication'] = $data['_3d_secure_authentication'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        $allowedValues = $this->getProcessorAllowableValues();
        if (!is_null($this->container['processor']) && !in_array($this->container['processor'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'processor', must be one of '%s'",
                $this->container['processor'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tags
     *
     * @return array<string,string>|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param array<string,string>|null $tags Key value pair for annotating custom meta data (e.g. order numbers).
     *
     * @return self
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount The total amount that will be debited in cents (e.g. 100 cents to debit $1.00).
     *
     * @return self
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \Finix\Model\Currency
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \Finix\Model\Currency $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets idempotency_id
     *
     * @return string|null
     */
    public function getIdempotencyId()
    {
        return $this->container['idempotency_id'];
    }

    /**
     * Sets idempotency_id
     *
     * @param string|null $idempotency_id A randomly generated value that'll be associated with the request.
     *
     * @return self
     */
    public function setIdempotencyId($idempotency_id)
    {
        $this->container['idempotency_id'] = $idempotency_id;

        return $this;
    }

    /**
     * Gets merchant
     *
     * @return string|null
     */
    public function getMerchant()
    {
        return $this->container['merchant'];
    }

    /**
     * Sets merchant
     *
     * @param string|null $merchant The ID of the resource.
     *
     * @return self
     */
    public function setMerchant($merchant)
    {
        $this->container['merchant'] = $merchant;

        return $this;
    }

    /**
     * Gets merchant_identity
     *
     * @return string|null
     */
    public function getMerchantIdentity()
    {
        return $this->container['merchant_identity'];
    }

    /**
     * Sets merchant_identity
     *
     * @param string|null $merchant_identity The ID of the resource.
     *
     * @return self
     */
    public function setMerchantIdentity($merchant_identity)
    {
        $this->container['merchant_identity'] = $merchant_identity;

        return $this;
    }

    /**
     * Gets processor
     *
     * @return string|null
     */
    public function getProcessor()
    {
        return $this->container['processor'];
    }

    /**
     * Sets processor
     *
     * @param string|null $processor Name of the transaction processor.
     *
     * @return self
     */
    public function setProcessor($processor)
    {
        $allowedValues = $this->getProcessorAllowableValues();
        if (!is_null($processor) && !in_array($processor, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'processor', must be one of '%s'",
                    $processor,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['processor'] = $processor;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source The ID of the resource.
     *
     * @return self
     */
    public function setSource($source)
    {
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets additional_purchase_data
     *
     * @return \Finix\Model\AdditionalPurchaseData|null
     */
    public function getAdditionalPurchaseData()
    {
        return $this->container['additional_purchase_data'];
    }

    /**
     * Sets additional_purchase_data
     *
     * @param \Finix\Model\AdditionalPurchaseData|null $additional_purchase_data additional_purchase_data
     *
     * @return self
     */
    public function setAdditionalPurchaseData($additional_purchase_data)
    {
        $this->container['additional_purchase_data'] = $additional_purchase_data;

        return $this;
    }

    /**
     * Gets fraud_session_id
     *
     * @return string|null
     */
    public function getFraudSessionId()
    {
        return $this->container['fraud_session_id'];
    }

    /**
     * Sets fraud_session_id
     *
     * @param string|null $fraud_session_id The `fraud_session_session` ID you want to review for fraud. For more info, see [Fraud Detection](/docs/guides/payments/fraud-detection/).
     *
     * @return self
     */
    public function setFraudSessionId($fraud_session_id)
    {
        $this->container['fraud_session_id'] = $fraud_session_id;

        return $this;
    }

    /**
     * Gets sub_type
     *
     * @return \Finix\Model\SubTypeTransfer|null
     */
    public function getSubType()
    {
        return $this->container['sub_type'];
    }

    /**
     * Sets sub_type
     *
     * @param \Finix\Model\SubTypeTransfer|null $sub_type sub_type
     *
     * @return self
     */
    public function setSubType($sub_type)
    {
        $this->container['sub_type'] = $sub_type;

        return $this;
    }

    /**
     * Gets operation_key
     *
     * @return \Finix\Model\OperationKey|null
     */
    public function getOperationKey()
    {
        return $this->container['operation_key'];
    }

    /**
     * Sets operation_key
     *
     * @param \Finix\Model\OperationKey|null $operation_key operation_key
     *
     * @return self
     */
    public function setOperationKey($operation_key)
    {
        $this->container['operation_key'] = $operation_key;

        return $this;
    }

    /**
     * Gets device
     *
     * @return string|null
     */
    public function getDevice()
    {
        return $this->container['device'];
    }

    /**
     * Sets device
     *
     * @param string|null $device The ID of the resource.
     *
     * @return self
     */
    public function setDevice($device)
    {
        $this->container['device'] = $device;

        return $this;
    }

    /**
     * Gets additional_buyer_charges
     *
     * @return \Finix\Model\AdditionalBuyerCharges|null
     */
    public function getAdditionalBuyerCharges()
    {
        return $this->container['additional_buyer_charges'];
    }

    /**
     * Sets additional_buyer_charges
     *
     * @param \Finix\Model\AdditionalBuyerCharges|null $additional_buyer_charges additional_buyer_charges
     *
     * @return self
     */
    public function setAdditionalBuyerCharges($additional_buyer_charges)
    {
        $this->container['additional_buyer_charges'] = $additional_buyer_charges;

        return $this;
    }

    /**
     * Gets _3d_secure_authentication
     *
     * @return \Finix\Model\CreateAuthorizationRequest3dSecureAuthentication|null
     */
    public function get3dSecureAuthentication()
    {
        return $this->container['_3d_secure_authentication'];
    }

    /**
     * Sets _3d_secure_authentication
     *
     * @param \Finix\Model\CreateAuthorizationRequest3dSecureAuthentication|null $_3d_secure_authentication _3d_secure_authentication
     *
     * @return self
     */
    public function set3dSecureAuthentication($_3d_secure_authentication)
    {
        $this->container['_3d_secure_authentication'] = $_3d_secure_authentication;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


